name: bpref
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.4.0
  - cudatoolkit=10.1
  - absl-py
  - pyparsing
  - pip
  - pip:
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+git://github.com/facebookresearch/hydra@0.11_branch
    - matplotlib
    - glfw==1.11.2
    - scikit-image
